language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-get install cmake
    - sudo add-apt-repository universe
    - sudo apt-get update
    - sudo apt-get install libboost-all-dev

install:
    - sudo apt-get install libboost-all-dev zlib1g-dev libbz2-dev tar

before_script:
    - git submodule update --init
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=debug
    - make VERBOSE=1

script:
    - ctest -V

after_success:
    - tar -czf /home/travis/build/vladsaveliev-no2f/joinx/build.tar.gz /home/travis/build/vladsaveliev-no2f/joinx/build

deploy:
  provider: releases
  file: /home/travis/build/vladsaveliev-no2f/joinx/build.tar.gz
  skip_cleanup: true
#  user: vladsaveliev-no2f
#  password:
#    secure: KVElOrcqewmMAomIli6HvvEa2IWRUR11jceyi0uPoflnyiTEQTJgrE1tu3u1zc+Ru7aDdp3h39cjCBm4uYICXRU7LyW7AOZI1RYStciEmCuPZC7l2l0MQnT9Osq9UMPIUw4JhLErFU3DXtqArbM0kNHLyIo9dK383o0sUsWGm35aR33SYGxM2WQI4A/qofLhHgdg4ODG174RIq2HvXxeZmsSMgeknTIIMnHmSgHrAho3Bgu61lQmaIlVXx6vyIhEgUIyqD9Ly9ZHD3oys9Brym0KHLn3Bmpci600JABqANxvF8bm6sNfGrc8rU9skZo4Rgi08HVCCv7Zb5pOCUg/hSBMAje/lVMx9ao19IDmVjgJQ0mhL7IBoJxjU85gEhsyp6geJcg8349WQX6/69iVR5O4sId3Xz5aIVQRL33BqTLfAz2GobBfjKvN78a4U3MNmYD4KgYkWhbnoqciUXASUetEw6ULdPDei6HJAy7jj0+GltzIJrICL07jIwl3rmlSnWx1cENQycAKPd020HpniD8yEH1Zfo6b/c0JQBoTQ1I+cXQKiAjLfpPm1ZmZRsl5W4tRCu6g8pfK10kZaH07lkdtbgg/9EN5nt4iitKI/l2sGF5B2F200M26v7n8wXs2Yc5lOhXSMme8TF27x3tjSHV2LnQGvFot7QK1ZizZxUs=
  api_key:
    secure: "qajLwZ2+k5sfr9dMOKB1Hmijkiw8SQWvMddACbkjsNi/652aZ7Vz6ux7RGejbJkyF6oDK7TFQeN1oVG4bpWERnGZ0IPoLXAEvD62OMVnq8GtNR6U8DQ1gbfRTiOOElnGqSiLGfOqyUplbkmXwsENjmPER9/q86cKI+ekgbkueNZ/+LrAz4wN+YD1R1TdPC32mj8efy+sIkqiEKZXDwzdEgUogJ1G7SwBu3fUxGlOB5kamdEI5jjucs6UXGyvMuyw+hvs7R7AAELkMvqy+HUG55QRaCjvbpksLdNa3GprsFcEffkiMFnGiBA1D46NscMhncTJkQvodxI/4xR1oeqqYA9WCREmVEuWOd7l5Ep3NM9Xbn3+8wzpou/q9LMf9aOqGM8jc/eaNUrHZonI2VZyKEAwXGy2FQ3Bv8fCLsml1fxKLYNO8mRv8t9b5Jcz1GU9ixHcnH+yNryEEhxmnaxal4rJVWEhvV91QqYFpudPGie7g3Tufsj0N0sfo3ze+Rbfu87HcL8/VU8hm2tLa1ca01VnRCS4LVol3gy3Aeq7+mLavudc1T9KFEa9ixbSWvVkT5R0pZpQoXA3w22hYG9ihtkaNwYZbE6rMSZ5Q35sZanMxrK9GiAJ3AL/ica/6B8+VxfoT8wEiUNE6PPnQedAJOuWTECRiYO4B3y3B3uibkc="